// PROFILE
export const GET_LIST_POKEMON_LOADING = "GET_LIST_POKEMON_LOADING";
export const GET_LIST_POKEMON_SUCCESS = "GET_LIST_POKEMON_SUCCESS";

export const GET_POKEMON_BY_ID_LOADING = "GET_POKEMON_BY_ID_LOADING";
export const GET_POKEMON_BY_ID_SUCCESS = "GET_POKEMON_BY_ID_SUCCESS";